name: CI-tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '5.0'


      - run: pip3 install -r requirements.txt

      - run: npm install
      - run: npm run build --if-present
      - run: npm test

      - run: pytest
